/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef store_CONSTANTS_H
#define store_CONSTANTS_H

#include "store_types.h"



class storeConstants {
 public:
  storeConstants();

};

extern const storeConstants g_store_constants;



#endif
