/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef store_TYPES_H
#define store_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>




class meta;

class node_info;

typedef struct _meta__isset {
  _meta__isset() : timestamp(false), success(false), ip(false), port(false), result(false) {}
  bool timestamp :1;
  bool success :1;
  bool ip :1;
  bool port :1;
  bool result :1;
} _meta__isset;

class meta : public virtual ::apache::thrift::TBase {
 public:

  meta(const meta&);
  meta& operator=(const meta&);
  meta() : timestamp(0), success(0), ip(), port(0), result() {
  }

  virtual ~meta() noexcept;
  int32_t timestamp;
  bool success;
  std::string ip;
  int16_t port;
  std::string result;

  _meta__isset __isset;

  void __set_timestamp(const int32_t val);

  void __set_success(const bool val);

  void __set_ip(const std::string& val);

  void __set_port(const int16_t val);

  void __set_result(const std::string& val);

  bool operator == (const meta & rhs) const
  {
    if (!(timestamp == rhs.timestamp))
      return false;
    if (!(success == rhs.success))
      return false;
    if (!(ip == rhs.ip))
      return false;
    if (!(port == rhs.port))
      return false;
    if (!(result == rhs.result))
      return false;
    return true;
  }
  bool operator != (const meta &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const meta & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(meta &a, meta &b);

std::ostream& operator<<(std::ostream& out, const meta& obj);

typedef struct _node_info__isset {
  _node_info__isset() : ip(false), port(false) {}
  bool ip :1;
  bool port :1;
} _node_info__isset;

class node_info : public virtual ::apache::thrift::TBase {
 public:

  node_info(const node_info&);
  node_info& operator=(const node_info&);
  node_info() : ip(), port(0) {
  }

  virtual ~node_info() noexcept;
  std::string ip;
  int16_t port;

  _node_info__isset __isset;

  void __set_ip(const std::string& val);

  void __set_port(const int16_t val);

  bool operator == (const node_info & rhs) const
  {
    if (!(ip == rhs.ip))
      return false;
    if (!(port == rhs.port))
      return false;
    return true;
  }
  bool operator != (const node_info &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const node_info & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(node_info &a, node_info &b);

std::ostream& operator<<(std::ostream& out, const node_info& obj);



#endif
